---
deployment:
  tasks:
    - /bin/cp -Rf backend/. /home/vayunexs/api.web.vayunexsolution.com/
    - /bin/cp -Rf build/. /home/vayunexs/public_html/
    - /bin/cp -Rf admin-panel/. /home/vayunexs/adminx.vayunexsolution.com/
